version: "3.7"

services:
  ############
  # Database #
  ############
  postgres:
    image: postgres
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5432}:5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - ./postgresql.conf:/etc/postgresql/postgresql.conf

  postgres-exporter:
    image: wrouesnel/postgres_exporter:latest
    restart: always
    depends_on:
      - postgres
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:${POSTGRES_PASSWORD:-changeme}@postgres:5432/postgres?sslmode=disable
    ports:
      - "${POSTGRES_EXPORTER_EXTERNAL_PORT:-9187}:9187"
